CREATE TABLE USUARIO (
ID_USUARIO INT (5) NOT NULL UNIQUE auto_increment PRIMARY KEY,
NOME_USUARIO VARCHAR (55) NOT NULL,
SEXO_USUARIO CHAR(1),
TELEFONE_USUARIO VARCHAR (16) NOT NULL,
EMAIL_USUARIO VARCHAR(50) NOT NULL,
STATUS_USUARIO VARCHAR(20) NOT NULL DEFAULT 'PENDENTE'
);